---
- name: .deb do update and upgrade
  apt: >
    update_cache=yes
    cache_valid_time=1200
    upgrade=safe

- name: install required packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ basic_packages }}"

- name: install Django
  pip:
    executable: pip3
    name: Django, virtualenv

- name: create code directory
  file:
    path: /var/www/text-assembler
    state: directory
    mode: '0755'

- name: clone repository
  git:
    clone: yes
    dest: /var/www/text-assembler
    repo: https://github.com/mlibrary/text-assembler-django.git

- name: install dependencies
  pip:
    chdir: /var/www/text-assembler
    virtualenv: ta_env
    requirements: requirements.txt

