---
- name: create code directory
  file:
    path: /var/www/text-assembler
    state: directory
    mode: '0755'

- name: clone repository
  git:
    clone: yes
    dest: /var/www/text-assembler
    repo: https://github.com/mlibrary/text-assembler-django.git
    version: cosign

- name: install dependencies
  pip:
    chdir: /var/www/text-assembler
    virtualenv: ta_env
    requirements: requirements.txt

# Configure application
- name: Copy about page
  copy:
    src: /var/www/text-assembler/textassembler_web/templates/textassembler_web/about.html.example
    dest: /var/www/text-assembler/textassembler_web/templates/textassembler_web/about.html
    remote_src: yes

- name: Copy footer page
  copy:
    src: /var/www/text-assembler/textassembler_web/templates/footer.html.example
    dest: /var/www/text-assembler/textassembler_web/templates/footer.html
    remote_src: yes

- name: Copy base page
  copy:
    src: /var/www/text-assembler/textassembler_web/templates/base.html.example
    dest: /var/www/text-assembler/textassembler_web/templates/base.html
    remote_src: yes

- name: Copy header page
  copy:
    src: /var/www/text-assembler/textassembler_web/templates/header.html.example
    dest: /var/www/text-assembler/textassembler_web/templates/header.html
    remote_src: yes

- name: Copy config
  template:
    src: textassembler.cfg.example
    dest: /var/www/text-assembler/textassembler.cfg

- name: Set up database
  shell:
    cmd: "ta_env/bin/python manage.py migrate"
    chdir: /var/www/text-assembler

- name: Copy textassembler etc files to init.d
  copy:
    remote_src: yes
    src: /var/www/text-assembler/etc/init.d/
    dest: /etc/init.d/

- name: make tassemblerd executable
  file:
    path: /etc/init.d/tassemblerd
    mode: 0755
- name: enable tassemblerd
  command: systemctl enable tassemblerd
- name: start tassemblerd
  systemd:
    name: tassemblerd
    state: started
    enabled: yes
    daemon-reload: yes

- name: make tassemblerzipd executable
  file:
    path: /etc/init.d/tassemblerzipd
    mode: 0755
- name: enable tassemblerzipd
  command: systemctl enable tassemblerzipd
- name: start tassemblerzipd
  systemd:
    name: tassemblerzipd
    state: started
    enabled: yes

- name: make tassemblerdeld executable
  file:
    path: /etc/init.d/tassemblerdeld
    mode: 0755
- name: enable tassemblerdeld
  command: systemctl enable tassemblerdeld
- name: start tassemblerdeld
  systemd:
    name: tassemblerdeld
    state: started
    enabled: yes

- name: Add cron job to update sources and API limits
  blockinfile:
    create: yes
    path: /etc/crontab
    block: |
      @monthly    root        /var/www/text-assembler/ta_env/bin/python /var/www/text-assembler/manage.py update_sources
      @monthly    root        /var/www/text-assembler/ta_env/bin/python /var/www/text-assembler/manage.py update_limits

- name: Create mysql script to create initial admin interface user
  template:
    src: admin_user.sql
    dest: /tmp/admin_user.sql

- name: Create initial admin interface user
  mysql_db:
    name: "{{ MYSQL_DB_NAME }}"
    login_user: "{{ MYSQL_DB_USER }}"
    login_password: "{{ MYSQL_DB_PASSWORD }}"
    state: import
    target: /tmp/admin_user.sql

- name: Initialize limits in database
  shell:
    cmd: "ta_env/bin/python manage.py update_limits"
    chdir: /var/www/text-assembler

- name: Collect static files
  shell:
    cmd: "ta_env/bin/python manage.py collectstatic"
    chdir: /var/www/text-assembler

- name: Initialize sources in database
  shell:
    cmd: "ta_env/bin/python manage.py update_sources"
    chdir: /var/www/text-assembler
