---
# cp etc/init.d/* /etc/init.d/
- name: Copy textassembler etc files to init.d
  copy:
    remote_src: yes
    src: /var/www/text-assembler/etc/init.d/
    dest: /etc/init.d/
# systemctl daemon-reload
# systemctl enable tassemblerd
# systemctl start tassemblerd
- name: make tassemblerd executable
  file:
    path: /etc/init.d/tassemblerd
    mode: 0755
- name: enable tassemblerd
  command: systemctl enable tassemblerd
- name: start and enable tassemblerd
  systemd:
    name: tassemblerd
    state: started
    enabled: yes
    daemon-reload: yes
# systemctl enable tassemblerzipd
# systemctl start tassemblerzipd
- name: make tassemblerzipd executable
  file:
    path: /etc/init.d/tassemblerzipd
    mode: 0755
- name: enable tassemblerzipd
  command: systemctl enable tassemblerzipd
- name: start and enable tassemblerzipd
  systemd:
    name: tassemblerzipd
    state: started
    enabled: yes
# systemctl enable tassemblerdeld
# systemctl start tassemblerdeld
- name: make tassemblerdeld executable
  file:
    path: /etc/init.d/tassemblerdeld
    mode: 0755
- name: enable tassemblerdeld
  command: systemctl enable tassemblerdeld
- name: start and enable tassemblerdeld
  systemd:
    name: tassemblerdeld
    state: started
    enabled: yes
# edit crontab
- name: Add cron job to update sources and API limits
  blockinfile:
    create: yes
    path: /etc/crontab
    block: |
      @monthly    root        /var/www/text-assembler/ta_env/bin/python /var/www/text-assembler/manage.py update_sources
      @monthly    root        /var/www/text-assembler/ta_env/bin/python /var/www/text-assembler/manage.py update_limits

